add shop component
TarasKanf/woodcarv pull request #2
Opened 2020-03-13 08:25 UTC by khvalbotaihor

fix link highlighting

2020-03-19 21:53 UTC, TarasKanf requested changes

2020-03-19 21:53 UTC, TarasKanf commented on woodcarv/package-lock.json
> +            "mamacro": "^0.0.3"
Цей файлик зазвичай не треба комітити. 
Почитай собі про нього і для чого він. Бажано щоб там одразу про package.json щось розповіли

2020-03-19 21:53 UTC, TarasKanf commented on woodcarv/package.json
> +    "angular-animate": "^1.7.9",
також бажано знати для чого тут цей значок ^ і як воно впливає фактичну встановлену версію за допомогою команди npm install

2020-03-19 21:53 UTC, TarasKanf commented on woodcarv/src/app/menu/menu.component.less
> +.active {color:#FFF !important};
!important краще уникати. Це погана практина. 
Почитай це щоб зразуміти вміти правильно перекривати стилі і вираховувати який стиль буде накладатись. Дуже раджу, інакше буде муки з css
https://www.smashingmagazine.com/2007/07/css-specificity-things-you-should-know/

2020-03-19 21:53 UTC, TarasKanf commented on woodcarv/src/app/shop/shop.component.html
> +          <img src="{{ shopElement.image_src }}" alt="Image" class="img-fluid">
Краще так [src]="shopElement.image_src"
https://stackoverflow.com/questions/40797925/how-to-bind-img-src-in-angular-2-in-ngfor/40799136

2020-03-19 21:53 UTC, TarasKanf commented on woodcarv/src/app/shop/shop.component.html
> +        <h3 class="mb-0" ><a href="#">{{ shopElement.name }} </a></h3>
Якщо клікнути на name, воно часом не перенаправляє тебе на дефолтну сторінку ?

2020-03-19 21:53 UTC, TarasKanf commented on woodcarv/src/app/shop/shop.component.html
> +<!--End of the page content-->
Такі коментарі зайві зазвичай)

2020-03-19 21:53 UTC, TarasKanf commented on woodcarv/src/app/shop/shop.component.ts
> +import { ShopService } from '../shop.service';
тут треба вказувати повний шлях. Особливо у випадку сервісів. Відносні шляхи можуть перетворитись в кашу і важко підтримувати, якщо щось переносиш. А це стається частенько

2020-03-19 21:53 UTC, TarasKanf commented on woodcarv/src/assets/shopEl.json
> +      "image_src" : "assets/images/img_1.jpg"
image_src погана назва проперті. в js прийнято називати проперті camelCase стилі без будь-яких знаків.
мало б бути imageSrc

2020-03-28 21:51 UTC, khvalbotaihor commented on woodcarv/src/app/shop/shop.component.html
> +        <h3 class="mb-0" ><a href="#">{{ shopElement.name }} </a></h3>
так, воно веде на дефолтну строніку, але тоді питання, чи має вона кудись вести, якщо має, то тоді питання куди вона має вести

2020-03-29 12:14 UTC, TarasKanf approved these changes

2020-03-29 12:15 UTC, merged